--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/blackbarbar/AreaBreak
build-by-default: true
branches:
- master
projects:
 AreaBreak:
    path: ""
    libs:
        version: 1.0.0
...
